version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: gunicorn --bind 0.0.0.0:8000 your_project_name.wsgi:application
    restart: always
    volumes:
      - static:/app/static
      - media:/app/media
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
      - redis
    env_file:
      - env/.env
    networks:
      - app-network

  db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - env/.env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  mongo:
    image: mongo:6.0
    restart: always
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  redis:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  postgres_data:
  mongodata:
  static:
  media:
  redis_data:

networks:
  app-network:
    driver: bridge
