version: '3.8'

services:
  django:
    build:
      context: .
    container_name: django_app
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - env/.env

  celery:
    build:
      context: .
    container_name: celery_worker
    command: celery -A project worker --loglevel=info
    depends_on:
      - redis
      - db
    volumes:
      - .:/app
    env_file:
      - env/.env

  flower:
    build:
      context: .
    container_name: celery_flower
    command: celery -A project flower --port=5555
    depends_on:
      - redis
    ports:
      - "5555:5555"
    env_file:
      - env/.env

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
    env_file:
      - env/.env

  db:
    image: postgres:15-alpine
    container_name: db
    expose:
      - "5433"
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - env/.env

volumes:
  postgres_data:
